services:

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - node-app
    networks:
      - node-network

  node-app:
    build:
      context: node
    container_name: node-app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      # Volume anônimo
      - /usr/src/app/node_modules
    tty: true
    ports:
     - "3000:3000"

  db:
    image: mysql:8.0.36
    container_name: db
    restart: always
    tty: true
    volumes:
      # volume nomeado
      - mysql_data:/var/lib/mysql      
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mysql_data:
